/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // DESIGN.md canonical — sumber kebenaran
        primary: "#0F7A4A",
        "primary-pressed": "#0B5C38",
        danger: "#C62828",
        "critical-red": "#C62828",
        warning: "#EF6C00",
        caution: "#F9A825",
        safe: "#4edea3",
        "safe-bg": "#E8F5E9",
        "success-bg": "#E8F5E9",
        "error-bg": "#FFEBEE",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        surface: "#FFFFFF",
        "surface-muted": "#F5F5F0",
        "text-primary": "#1A1A1A",
        "text-secondary": "#595959",
        border: "#D9D9D9",
        // ui-docs 4 html — dipakai nyata (pruned legacy Stitch)
        background: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#FFFFFF",
        "border-subtle": "#E2E8F0",
        "slate-gray": "#64748B",
        "on-primary": "#ffffff",
        "primary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#bcc7de",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#ffddb8",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45474c",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#3c475a",
        outline: "#75777d",
        "outline-variant": "#c5c6cd",
        "tertiary-fixed": "#6ffbbe",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "margin-mobile": "16px",
        "gutter-mobile": "12px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "data-mono": ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        headline: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#0F7A4A",
          "primary-content": "#FFFFFF",
          secondary: "#F5F5F0",
          accent: "#0F7A4A",
          neutral: "#1A1A1A",
          "base-100": "#FFFFFF",
          "base-200": "#F5F5F0",
          "base-300": "#D9D9D9",
          info: "#0F7A4A",
          success: "#0F7A4A",
          warning: "#EF6C00",
          error: "#C62828",
        },
      },
      "light",
    ],
    darkTheme: "light",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: false,
  },
};
